import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { MessageProvider } from "@/components/MessageProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MessageProvider>
          <header
            style={{
              borderBottom: "1px solid var(--border)",
              padding: "12px 16px",
            }}
          >
            <nav
              style={{
                maxWidth: 920,
                margin: "0 auto",
                display: "flex",
                gap: 12,
                alignItems: "center",
              }}
            >
              <Link
                href="/"
                style={{
                  fontWeight: 600,
                  color: "var(--foreground)",
                  textDecoration: "none",
                }}
              >
                Chat
              </Link>
              <Link
                href="/ingest"
                style={{ color: "var(--foreground)", textDecoration: "none" }}
              >
                Ingest
              </Link>
              <Link
                href="/documents"
                style={{ color: "var(--foreground)", textDecoration: "none" }}
              >
                Documents
              </Link>
            </nav>
          </header>
          <div>{children}</div>
        </MessageProvider>
      </body>
    </html>
  );
}
